### ISSUE TITLE
poolmgr for nodejs crash looping

### ISSUE THREAD

**Issue by ggilley** [fission/fission#1635]
Running version 1.9.0

I'm getting a crashloop in poolmgr with nodejs. It looks like there was a check added before when making the symlink to make sure it doesn't already exist. Does anyone know why it was removed?

[https://github.com/yqf3139/fission/commit/566960d47f65cfa3b8715ddb449b164573598c94](url)

`\n\n","errorVerbose":"Internal error - \n\n\n\nError\n\n\n
Error: EEXIST: file already exists, symlink '/usr/src/app/node_modules' -> '/userfunc/node_modules'
    at Object.fs.symlinkSync (fs.js:1014:18)
    at specialize (/usr/src/app/server.js:86:8)
    at /usr/src/app/server.js:49:9
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
\n\n\nerror specializing function pod\ngithub.com/fission/fission/pkg/fetcher.(*Fetcher).SpecializePod\n\t/go/src/pkg/fetcher/fetcher.go:652\ngithub.com/fission/fission/pkg/fetcher.(*Fetcher).SpecializeHandler\n\t/go/src/pkg/fetcher/fetcher.go:197\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2375\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","stacktrace":"github.com/fission/fission/pkg/fetcher.(*Fetcher).SpecializeHandler\n\t/go/src/pkg/fetcher/fetcher.go:199\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2375\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878"}`

**Comment by vishal-biyani** [comment]
Hi @ggilley I am not able to reproduce with a simple NodeJS function. Can you please share more details. I will meantime check the reason for removing the check.

**Comment by ggilley** [comment]
We are trying to implement the multi tenancy described in [https://github.com/fission/fission/blob/master/Documentation/wip/Multi-tenancy.md](url)

We separated the environment creation from the rest of the package and function creation. In doing so, we lost the annotations for `fission-name` and `fission-uid`. This caused it to crashloop.

We are still trying to get all of the pieces working. I was just wondering why this particular protection had been removed since we seemed to have triggered this problem :-)

**Comment by funkypenguin** [comment]
Hey folks, I work with @ggilley,

The root cause of the issue was that we'd omitted `  version: 2` from the environment YAML spec. This line was the only difference between a working and a broken environment :)

Cheers!
D

**Comment by vishal-biyani** [comment]
Hey @funkypenguin thanks for confirming and glad that issue is resolved. Closing this issue.

**Comment by ggilley** [comment]
I see you closed it. But it still crash looped with an error. It seems like it would be better at handling the errors more gracefully. That's really what I was asking about. There was code that helped to prevent the crash loop that was removed.

**Comment by vishal-biyani** [comment]
Hey @ggilley I thought it was solved - but if it is happening, I am open to keeping the issue for further investigation.

**Comment by ggilley** [comment]
Our issue is solved. I don’t thing fission should crash loop because we had an error in a version for an environment.

**Comment by jahredhope** [comment]
I believe I'm experiencing the same issue.
I'm attempting to setup my first few functions and am making mistakes as I do. The errors caused by the repeated calls to `symlinkSync` make it look like the error isn't in my code leading, to a wild goose chase when the real issue was `export` vs `module.exports`.

This seems like quite a common scenario (developer's writing code that doesn't work, especially when learning the system), and at best makes it difficult to read the logs, but more likely leaves the developer thinking the underlying issue is with Fission.

I can see a PR was closed that would have put a guard on this call https://github.com/fission/fission/pull/258 would that be something that could be tried again?

**Comment by vishal-biyani** [comment]
Hi @jahredhope Thanks for the details and linking the relevant PR, I wasn't sure if it was related. I will get this prioritized for the next release (1.12)
