### ISSUE TITLE
Poolmgr deployments missing after restart of executor

### ISSUE THREAD

**Issue by davidsmf** [fission/fission#1640]
**Fission/Kubernetes version** 

Fission: 1.7.1
Kube: 1.14.9-eks

**Kubernetes platform (e.g. Google Kubernetes Engine)**

AWS/eks

**Describe the bug**

**To Reproduce**

Create many environments using poolmgr. We have 20.

Restart the executor container.

**Expected result**

All the functions continue to work.

**Actual result**

Some of the environments are missing a deployment, so the functions cannot start.

**Screenshots/Dump file**

```
{"level":"info","ts":1591707479.2292733,"caller":"executor/executor.go:231","msg":"Starting executor","instanceID":"dxa7rnle"}
{"level":"info","ts":1591707479.2293956,"logger":"generic_pool_manager","caller":"poolmgr/gpm.go:381","msg":"Poolmanager starts to clean orphaned resources","instanceID":"dxa7rnle"}
{"level":"info","ts":1591707479.2294748,"logger":"new_deploy","caller":"newdeploy/newdeploymgr.go:277","msg":"Newdeploy starts to clean orphaned resources","instanceID":"dxa7rnle"}
{"level":"info","ts":1591707479.2446375,"logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:100","msg":"creating pool","environment":{"name":"mf-1-8-0","namespace":"cs","selfLink":"/apis/fission.io/v1/namespaces/cs/environments/mf-1-8-0","uid":"0302b38f-aa36-11ea-9dbe-02dd6e8c4832","resourceVersion":"112585481","generation":1,"creationTimestamp":"2020-06-09T09:45:54Z","annotations":{"fission-name":"","fission-uid":"mf-cs"}}}
{"level":"info","ts":1591707479.2628214,"logger":"generic_pool_manager","caller":"reaper/reaper.go:84","msg":"cleaning up deployment","deployment":"poolmgr-mf-1-8-0-XXXX-100035800"}
{"level":"info","ts":1591707479.2759933,"logger":"generic_pool_manager","caller":"reaper/reaper.go:84","msg":"cleaning up deployment","deployment":"poolmgr-mf-1-8-0-cs-112585481"}
```

**Additional context**

`adoptExistingResources` is false.

However the code in `func (gp *GenericPool) createPool()` will 'adopt' a deployment:
```
	depl, err := gp.kubernetesClient.AppsV1().Deployments(gp.namespace).Get(deployment.Name, metav1.GetOptions{})
	if err == nil {
		if depl.Annotations[fv1.EXECUTOR_INSTANCEID_LABEL] != gp.instanceId {
			deployment.Annotations[fv1.EXECUTOR_INSTANCEID_LABEL] = gp.instanceId
			depl, err = gp.kubernetesClient.AppsV1().Deployments(gp.namespace).Update(deployment)
		}
```

**Comment by vishal-biyani** [comment]
Hi, @davidsmf This was fixed in 1.8.0 (https://github.com/fission/fission/pull/1511) and I was not able to reproduce with 20 Env+functions with the latest release too. Would it be possible for you to upgrade to higher releases?

**Comment by davidsmf** [comment]
Thanks, I'll look at getting that upgrade done.

**Comment by mattroark** [comment]
@vishal-biyani Our environment is already on 1.8.0 and we still experienced this.
```
❯ fission version
client:
  fission/core:
    BuildDate: "2020-02-03T08:40:57Z"
    GitCommit: bda974a72c9093e241c1dae6a7fc1a2d16e28b02
    Version: 1.8.0
server:
  fission/core:
    BuildDate: "2020-02-03T08:40:57Z"
    GitCommit: bda974a72c9093e241c1dae6a7fc1a2d16e28b02
    Version: 1.8.0
```

**Comment by vishal-biyani** [comment]
Hi @mattroark I will reopen this so we can track, reproduce and fix this.

**Comment by mattroark** [comment]
Thanks! If any more info is needed from my side, or, if we encounter it again, I will report back.

**Comment by soharab-ic** [comment]
Closing the issue due to inactivity.
