### ISSUE TITLE
Go-env panic

### ISSUE THREAD

**Issue by havok4u** [fission/fission#222]
After successfully getting the go-env up (leveraging fission/go-env) I tried to launch a function and get a panic error:
$ kubectl --namespace fission-function logs go-runtime-0d9a3d78-d9cd-4e55-8b39-419817153e3e-ukb3uq0o-26ff51 go-runtime
Listening on 8888 ...
Specializing ...
2017/06/08 16:26:16 http: panic serving 10.38.0.3:35400: plugin.Open: plugin was built with a different version of package math
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc420110640)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x7e3480, 0xc420010f50)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.loadPlugin(0xc42007bc88)
	/usr/src/github.com/fission/fission/environments/go/server.go:21 +0x45e
main.specializeHandler(0xb7f240, 0xc42012c000, 0xc42000aa00)
	/usr/src/github.com/fission/fission/environments/go/server.go:64 +0x1c0
net/http.HandlerFunc.ServeHTTP(0x848e38, 0xb7f240, 0xc42012c000, 0xc42000aa00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xba2640, 0xb7f240, 0xc42012c000, 0xc42000aa00)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200da2c0, 0xb7f240, 0xc42012c000, 0xc42000aa00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420110640, 0xb7f740, 0xc420018440)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

Details of Implemention:
hello.go
==================================
package main

import (
    "net/http"
)

func Handler(w http.ResponseWriter, r *http.Request) {
    msg := "Hello, World!"
    w.Write([]byte(msg))
}
===================================

Compiled into a loadable object using golang 1.8.1 with the following command
go build --buildmode=plugin hello.go

Then created the service:

$ fission function create --name hello2 --env go-runtime --package hello.so

$ fission route create --method GET --url /hello2 --function hello2

$ curl http://127.0.0.1:31314/hello2
Internal server error (fission)

**Comment by soamvasani** [comment]
I guess plugins from different go versions are incompatible?  

I think the best approach here is to make a `go-builder` docker image to go with the `go-runtime` image, and keep their versions in sync.

**Comment by nouney** [comment]
If I recall correctly, that problem should be fixed in go 1.9.

**Comment by havok4u** [comment]
I re-built the go-env as 1.8.1 by modifying the dockerfile and rebuilding.  Then redeployed the environment and launched the service again. Still getting the error.  So not version of go in this instance.

**Comment by havok4u** [comment]
Here is the version I compiled with
go version go1.8.1 linux/amd64

Here is the version running in my go-runtime images
go version go1.8.1 linux/amd64

They are identical (but re last post still same issue)

**Comment by soamvasani** [comment]
@havok Can you build using the provided build helper script [`go-function-build`](https://github.com/fission/fission/blob/master/environments/go/builder/go-function-build)?  I just tested it and it still works.

**Comment by soamvasani** [comment]
@havok4u Can you test the latest?

If you have an existing environment you can update it

```
fission env update --name go-runtime --image fission/go-env:1.8.1
```

And you'll also have to re-download the [build helper script](https://raw.githubusercontent.com/fission/fission/master/environments/go/builder/go-function-build).

**Comment by soamvasani** [comment]
Ok we're all set, @havok4u tested the fix.

(Both the instructions and the helper script were clueless about versioning, the fix updates both those things.)
