### ISSUE TITLE
Timer pod is ends up in CrashLoopBackOff

### ISSUE THREAD

**Issue by laugmanuel** [fission/fission#2707]
**Fission/Kubernetes version**

- Kubernetes v1.21.6+vmware.1
- Fission v1.18.0

<pre>
❯ fission version
client:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
server:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:50:34Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6+vmware.1", GitCommit:"d20434e6e816f03eb74ff47fbc4820a425fc200b", GitTreeState:"clean", BuildDate:"2021-11-02T02:12:40Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

VMware Tanzu for vSphere

**Describe the bug**

The fission pod ends up in `CrashLoopBackOff` with the following error messages:
```sh
❯ k logs timer-765c45b7dc-smvz8
2023-01-27T10:16:49.040Z	DEBUG	utils/namespace.go:49	namespaces	{"function_namespace": "", "builder_namespace": "", "default_namespace": "", "fission_resource_namespace": ["fission"]}
2023-01-27T10:16:49.059Z	INFO	otel/provider.go:50	OTEL_EXPORTER_OTLP_ENDPOINT not set, skipping Opentelemtry tracing
2023-01-27T10:16:49.060Z	INFO	crd/client.go:105	Waiting for CRDs to be installed
2023-01-27T10:17:19.149Z	ERROR	fission-bundle/main.go:288	timer exited	{"error": "error waiting for CRDs: timeout waiting for CRDs", "errorVerbose": "timeout waiting for CRDs\nerror waiting for CRDs\ngithub.com/fission/fission/pkg/timer.Start\n\tpkg/timer/main.go:38\nmain.runTimer\n\tcmd/fission-bundle/main.go:74\nmain.main\n\tcmd/fission-bundle/main.go:286\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/proc.go:250\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/asm_amd64.s:1594"}
main.main
	cmd/fission-bundle/main.go:288
runtime.main
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/proc.go:250
```

The CRDs are all present:
```sh
❯ k get crd | grep fission
canaryconfigs.fission.io                                           2023-01-27T08:27:39Z
environments.fission.io                                            2023-01-27T08:27:40Z
functions.fission.io                                               2023-01-27T08:27:41Z
httptriggers.fission.io                                            2023-01-27T08:27:41Z
kuberneteswatchtriggers.fission.io                                 2023-01-27T08:27:42Z
messagequeuetriggers.fission.io                                    2023-01-27T08:27:42Z
packages.fission.io                                                2023-01-27T08:27:42Z
timetriggers.fission.io                                            2023-01-27T08:27:42Z
```

**To Reproduce**

For me this happens after a fresh install of Fission following the official docs. I've retried installation and got the same result.

**Expected result**

Fission Timer is running

**Actual result**

Fission Timer is crashing due to above error

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

Regular functions are working; I've deployed the hello-world example and I can get the result using `fission function test`.

**Comment by krzwiatrzyk** [comment]
I've got the same, Kubernetes version v1.25, Fission v1.18.0, all CRDs installed:
`Waiting for CRDs to be installed`

**Comment by krzwiatrzyk** [comment]
It seems that the issue is related to `defaultNamespaces` parameter. I have deployed fission into `fission` namespace and set `defaultNamespace` to fission... changing it back to `default` helped.

**Comment by laugmanuel** [comment]
I can confirm that setting `defaultNamespaces` to `default` and all the other namespace parameters to `fission` also works and the pods seem to be happy.

**Comment by soharab-ic** [comment]
Please try latest fission version `v1.20.4` and re-open if issue remains.
